version: '3'
services:
  dynamodb:
    image: peopleperhour/dynamodb
    ports:
     - "8100:8000"
  development:
    build: .
    volumes:
      - .:/opt/MooseX-Storage-IO-AmazonDynamoDB
      - $HOME/.gitconfig:/home/app/.gitconfig
      - $HOME/.ssh/id_rsa:/home/app/.ssh/id_rsa
    env_file: .env
