version: '3'
services:
  dynamodb:
    image: peopleperhour/dynamodb
    ports:
     - "8100:8000"
  development:
    build: .
    volumes:
      - .:/home/app/MooseX-Storage-IO-AmazonDynamoDB
    env_file: .env
